Traceback (most recent call last):
  File "/root/autodl-tmp/index-tts-vllm/server/task_worker.py", line 24, in <module>
    from indextts.infer_vllm import IndexTTS
  File "/root/autodl-tmp/index-tts-vllm/indextts/infer_vllm.py", line 22, in <module>
    from indextts.gpt.model_vllm import UnifiedVoice
  File "/root/autodl-tmp/index-tts-vllm/indextts/gpt/model_vllm.py", line 4, in <module>
    import patch_vllm  # ⚠️ Monkey Patch, do not delete this line
    ^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/index-tts-vllm/patch_vllm.py", line 6, in <module>
    vllm_version = version.parse(importlib.import_module("vllm").__version__)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'vllm'
Traceback (most recent call last):
  File "/root/autodl-tmp/index-tts-vllm/server/task_worker.py", line 24, in <module>
    from indextts.infer_vllm import IndexTTS
  File "/root/autodl-tmp/index-tts-vllm/indextts/infer_vllm.py", line 22, in <module>
    from indextts.gpt.model_vllm import UnifiedVoice
  File "/root/autodl-tmp/index-tts-vllm/indextts/gpt/model_vllm.py", line 4, in <module>
    import patch_vllm  # ⚠️ Monkey Patch, do not delete this line
    ^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/index-tts-vllm/patch_vllm.py", line 6, in <module>
    vllm_version = version.parse(importlib.import_module("vllm").__version__)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'vllm'
Traceback (most recent call last):
  File "/root/autodl-tmp/index-tts-vllm/server/task_worker.py", line 24, in <module>
    from indextts.infer_vllm import IndexTTS
  File "/root/autodl-tmp/index-tts-vllm/indextts/infer_vllm.py", line 22, in <module>
    from indextts.gpt.model_vllm import UnifiedVoice
  File "/root/autodl-tmp/index-tts-vllm/indextts/gpt/model_vllm.py", line 4, in <module>
    import patch_vllm  # ⚠️ Monkey Patch, do not delete this line
    ^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/index-tts-vllm/patch_vllm.py", line 6, in <module>
    vllm_version = version.parse(importlib.import_module("vllm").__version__)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'vllm'
Traceback (most recent call last):
  File "/root/autodl-tmp/index-tts-vllm/server/task_worker.py", line 24, in <module>
    from indextts.infer_vllm import IndexTTS
  File "/root/autodl-tmp/index-tts-vllm/indextts/infer_vllm.py", line 22, in <module>
    from indextts.gpt.model_vllm import UnifiedVoice
  File "/root/autodl-tmp/index-tts-vllm/indextts/gpt/model_vllm.py", line 4, in <module>
    import patch_vllm  # ⚠️ Monkey Patch, do not delete this line
    ^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/index-tts-vllm/patch_vllm.py", line 6, in <module>
    vllm_version = version.parse(importlib.import_module("vllm").__version__)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'vllm'
INFO 09-26 15:48:51 [__init__.py:243] Automatically detected platform cuda.
✅  Registry GPT2TTSModel to vllm
✅  SamplingParams._verify_args Patched
✅  ModelInputForGPUBuilder._compute_lens Patched
Traceback (most recent call last):
  File "/root/autodl-tmp/index-tts-vllm/server/task_worker.py", line 29, in <module>
    from .database.db_manager import DatabaseManager
ImportError: attempted relative import with no known parent package
INFO 09-26 15:49:01 [__init__.py:243] Automatically detected platform cuda.
✅  Registry GPT2TTSModel to vllm
✅  SamplingParams._verify_args Patched
✅  ModelInputForGPUBuilder._compute_lens Patched
Traceback (most recent call last):
  File "/root/autodl-tmp/index-tts-vllm/server/task_worker.py", line 29, in <module>
    from .database.db_manager import DatabaseManager
ImportError: attempted relative import with no known parent package
INFO 09-26 15:49:13 [__init__.py:243] Automatically detected platform cuda.
✅  Registry GPT2TTSModel to vllm
✅  SamplingParams._verify_args Patched
✅  ModelInputForGPUBuilder._compute_lens Patched
Traceback (most recent call last):
  File "/root/autodl-tmp/index-tts-vllm/server/task_worker.py", line 29, in <module>
    from .database.db_manager import DatabaseManager
ImportError: attempted relative import with no known parent package
INFO 09-26 15:49:27 [__init__.py:243] Automatically detected platform cuda.
✅  Registry GPT2TTSModel to vllm
✅  SamplingParams._verify_args Patched
✅  ModelInputForGPUBuilder._compute_lens Patched
Traceback (most recent call last):
  File "/root/autodl-tmp/index-tts-vllm/server/task_worker.py", line 29, in <module>
    from .database.db_manager import DatabaseManager
ImportError: attempted relative import with no known parent package
INFO 09-26 15:49:37 [__init__.py:243] Automatically detected platform cuda.
✅  Registry GPT2TTSModel to vllm
✅  SamplingParams._verify_args Patched
✅  ModelInputForGPUBuilder._compute_lens Patched
Traceback (most recent call last):
  File "/root/autodl-tmp/index-tts-vllm/server/task_worker.py", line 29, in <module>
    from .database.db_manager import DatabaseManager
ImportError: attempted relative import with no known parent package
INFO 09-26 15:49:49 [__init__.py:243] Automatically detected platform cuda.
✅  Registry GPT2TTSModel to vllm
✅  SamplingParams._verify_args Patched
✅  ModelInputForGPUBuilder._compute_lens Patched
Traceback (most recent call last):
  File "/root/autodl-tmp/index-tts-vllm/server/task_worker.py", line 29, in <module>
    from .database.db_manager import DatabaseManager
ImportError: attempted relative import with no known parent package
INFO 09-26 15:50:01 [__init__.py:243] Automatically detected platform cuda.
✅  Registry GPT2TTSModel to vllm
✅  SamplingParams._verify_args Patched
✅  ModelInputForGPUBuilder._compute_lens Patched
Traceback (most recent call last):
  File "/root/autodl-tmp/index-tts-vllm/server/task_worker.py", line 29, in <module>
    from .database.db_manager import DatabaseManager
ImportError: attempted relative import with no known parent package
INFO 09-26 15:50:12 [__init__.py:243] Automatically detected platform cuda.
✅  Registry GPT2TTSModel to vllm
✅  SamplingParams._verify_args Patched
✅  ModelInputForGPUBuilder._compute_lens Patched
Traceback (most recent call last):
  File "/root/autodl-tmp/index-tts-vllm/server/task_worker.py", line 29, in <module>
    from .database.db_manager import DatabaseManager
ImportError: attempted relative import with no known parent package
INFO 09-26 15:50:23 [__init__.py:243] Automatically detected platform cuda.
✅  Registry GPT2TTSModel to vllm
✅  SamplingParams._verify_args Patched
✅  ModelInputForGPUBuilder._compute_lens Patched
Traceback (most recent call last):
  File "/root/autodl-tmp/index-tts-vllm/server/task_worker.py", line 29, in <module>
    from .database.db_manager import DatabaseManager
ImportError: attempted relative import with no known parent package
INFO 09-26 15:50:34 [__init__.py:243] Automatically detected platform cuda.
✅  Registry GPT2TTSModel to vllm
✅  SamplingParams._verify_args Patched
✅  ModelInputForGPUBuilder._compute_lens Patched
Traceback (most recent call last):
  File "/root/autodl-tmp/index-tts-vllm/server/task_worker.py", line 29, in <module>
    from .database.db_manager import DatabaseManager
ImportError: attempted relative import with no known parent package
INFO 09-26 15:50:47 [__init__.py:243] Automatically detected platform cuda.
✅  Registry GPT2TTSModel to vllm
✅  SamplingParams._verify_args Patched
✅  ModelInputForGPUBuilder._compute_lens Patched
Traceback (most recent call last):
  File "/root/autodl-tmp/index-tts-vllm/server/task_worker.py", line 29, in <module>
    from .database.db_manager import DatabaseManager
ImportError: attempted relative import with no known parent package
INFO 09-28 15:59:16 [__init__.py:216] Automatically detected platform cuda.
✅  Registry GPT2TTSModel to vllm
✅  GPUModelRunner._prepare_inputs Patched
Traceback (most recent call last):
  File "/root/autodl-tmp/indexTTS/server/task_worker.py", line 38, in <module>
    from .database.db_manager import DatabaseManager
ImportError: attempted relative import with no known parent package
INFO 09-28 15:59:26 [__init__.py:216] Automatically detected platform cuda.
✅  Registry GPT2TTSModel to vllm
✅  GPUModelRunner._prepare_inputs Patched
Traceback (most recent call last):
  File "/root/autodl-tmp/indexTTS/server/task_worker.py", line 38, in <module>
    from .database.db_manager import DatabaseManager
ImportError: attempted relative import with no known parent package
INFO 09-28 15:59:37 [__init__.py:216] Automatically detected platform cuda.
✅  Registry GPT2TTSModel to vllm
✅  GPUModelRunner._prepare_inputs Patched
Traceback (most recent call last):
  File "/root/autodl-tmp/indexTTS/server/task_worker.py", line 38, in <module>
    from .database.db_manager import DatabaseManager
ImportError: attempted relative import with no known parent package
INFO 09-28 15:59:47 [__init__.py:216] Automatically detected platform cuda.
✅  Registry GPT2TTSModel to vllm
✅  GPUModelRunner._prepare_inputs Patched
Traceback (most recent call last):
  File "/root/autodl-tmp/indexTTS/server/task_worker.py", line 38, in <module>
    from .database.db_manager import DatabaseManager
ImportError: attempted relative import with no known parent package
INFO 09-28 15:59:58 [__init__.py:216] Automatically detected platform cuda.
✅  Registry GPT2TTSModel to vllm
✅  GPUModelRunner._prepare_inputs Patched
Traceback (most recent call last):
  File "/root/autodl-tmp/indexTTS/server/task_worker.py", line 38, in <module>
    from database.db_manager import DatabaseManager
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: attempted relative import with no known parent package
INFO 09-28 16:00:08 [__init__.py:216] Automatically detected platform cuda.
✅  Registry GPT2TTSModel to vllm
✅  GPUModelRunner._prepare_inputs Patched
Traceback (most recent call last):
  File "/root/autodl-tmp/indexTTS/server/task_worker.py", line 38, in <module>
    from database.db_manager import DatabaseManager
  File "/root/autodl-tmp/indexTTS/server/database/db_manager.py", line 11, in <module>
    from ..utils.file_manager import TaskFileManager
ImportError: attempted relative import beyond top-level package
INFO 09-28 16:00:20 [__init__.py:216] Automatically detected platform cuda.
✅  Registry GPT2TTSModel to vllm
✅  GPUModelRunner._prepare_inputs Patched
Traceback (most recent call last):
  File "/root/autodl-tmp/indexTTS/server/task_worker.py", line 38, in <module>
    from database.db_manager import DatabaseManager
  File "/root/autodl-tmp/indexTTS/server/database/db_manager.py", line 11, in <module>
    from ..utils.file_manager import TaskFileManager
ImportError: attempted relative import beyond top-level package
INFO 09-28 16:00:44 [__init__.py:216] Automatically detected platform cuda.
✅  Registry GPT2TTSModel to vllm
✅  GPUModelRunner._prepare_inputs Patched
Traceback (most recent call last):
  File "/root/autodl-tmp/indexTTS/server/task_worker.py", line 38, in <module>
    from database.db_manager import DatabaseManager
  File "/root/autodl-tmp/indexTTS/server/database/db_manager.py", line 11, in <module>
    from ..utils.file_manager import TaskFileManager
ImportError: attempted relative import beyond top-level package
INFO 09-28 16:00:54 [__init__.py:216] Automatically detected platform cuda.
✅  Registry GPT2TTSModel to vllm
✅  GPUModelRunner._prepare_inputs Patched
Traceback (most recent call last):
  File "/root/autodl-tmp/indexTTS/server/task_worker.py", line 38, in <module>
    from database.db_manager import DatabaseManager
  File "/root/autodl-tmp/indexTTS/server/database/db_manager.py", line 11, in <module>
    from ..utils.file_manager import TaskFileManager
ImportError: attempted relative import beyond top-level package
INFO 09-28 16:01:04 [__init__.py:216] Automatically detected platform cuda.
✅  Registry GPT2TTSModel to vllm
✅  GPUModelRunner._prepare_inputs Patched
Traceback (most recent call last):
  File "/root/autodl-tmp/indexTTS/server/task_worker.py", line 38, in <module>
    from database.db_manager import DatabaseManager
  File "/root/autodl-tmp/indexTTS/server/database/db_manager.py", line 11, in <module>
    from ..utils.file_manager import TaskFileManager
ImportError: attempted relative import beyond top-level package
INFO 09-28 16:01:15 [__init__.py:216] Automatically detected platform cuda.
✅  Registry GPT2TTSModel to vllm
✅  GPUModelRunner._prepare_inputs Patched
Traceback (most recent call last):
  File "/root/autodl-tmp/indexTTS/server/task_worker.py", line 38, in <module>
    from database.db_manager import DatabaseManager
  File "/root/autodl-tmp/indexTTS/server/database/db_manager.py", line 11, in <module>
    from ..utils.file_manager import TaskFileManager
ImportError: attempted relative import beyond top-level package
INFO 09-28 16:01:28 [__init__.py:216] Automatically detected platform cuda.
✅  Registry GPT2TTSModel to vllm
✅  GPUModelRunner._prepare_inputs Patched
Traceback (most recent call last):
  File "/root/autodl-tmp/indexTTS/server/task_worker.py", line 38, in <module>
    from database.db_manager import DatabaseManager
  File "/root/autodl-tmp/indexTTS/server/database/db_manager.py", line 11, in <module>
    from ..utils.file_manager import TaskFileManager
ImportError: attempted relative import beyond top-level package
INFO 09-28 16:01:41 [__init__.py:216] Automatically detected platform cuda.
✅  Registry GPT2TTSModel to vllm
✅  GPUModelRunner._prepare_inputs Patched
Traceback (most recent call last):
  File "/root/autodl-tmp/indexTTS/server/task_worker.py", line 38, in <module>
    from database.db_manager import DatabaseManager
  File "/root/autodl-tmp/indexTTS/server/database/db_manager.py", line 11, in <module>
    from ..utils.file_manager import TaskFileManager
ImportError: attempted relative import beyond top-level package
INFO 09-28 16:01:52 [__init__.py:216] Automatically detected platform cuda.
✅  Registry GPT2TTSModel to vllm
✅  GPUModelRunner._prepare_inputs Patched
Traceback (most recent call last):
  File "/root/autodl-tmp/indexTTS/server/task_worker.py", line 38, in <module>
    from database.db_manager import DatabaseManager
  File "/root/autodl-tmp/indexTTS/server/database/db_manager.py", line 11, in <module>
    from ..utils.file_manager import TaskFileManager
ImportError: attempted relative import beyond top-level package
INFO 09-28 16:02:03 [__init__.py:216] Automatically detected platform cuda.
✅  Registry GPT2TTSModel to vllm
✅  GPUModelRunner._prepare_inputs Patched
Traceback (most recent call last):
  File "/root/autodl-tmp/indexTTS/server/task_worker.py", line 38, in <module>
    from database.db_manager import DatabaseManager
  File "/root/autodl-tmp/indexTTS/server/database/db_manager.py", line 11, in <module>
    from ..utils.file_manager import TaskFileManager
ImportError: attempted relative import beyond top-level package
INFO 09-28 16:02:14 [__init__.py:216] Automatically detected platform cuda.
✅  Registry GPT2TTSModel to vllm
✅  GPUModelRunner._prepare_inputs Patched
Traceback (most recent call last):
  File "/root/autodl-tmp/indexTTS/server/task_worker.py", line 38, in <module>
    from database.db_manager import DatabaseManager
  File "/root/autodl-tmp/indexTTS/server/database/db_manager.py", line 11, in <module>
    from ..utils.file_manager import TaskFileManager
ImportError: attempted relative import beyond top-level package
INFO 09-28 16:02:25 [__init__.py:216] Automatically detected platform cuda.
✅  Registry GPT2TTSModel to vllm
✅  GPUModelRunner._prepare_inputs Patched
Traceback (most recent call last):
  File "/root/autodl-tmp/indexTTS/server/task_worker.py", line 38, in <module>
    from database.db_manager import DatabaseManager
  File "/root/autodl-tmp/indexTTS/server/database/db_manager.py", line 11, in <module>
    from ..utils.file_manager import TaskFileManager
ImportError: attempted relative import beyond top-level package
INFO 09-28 16:02:36 [__init__.py:216] Automatically detected platform cuda.
✅  Registry GPT2TTSModel to vllm
✅  GPUModelRunner._prepare_inputs Patched
Traceback (most recent call last):
  File "/root/autodl-tmp/indexTTS/server/task_worker.py", line 38, in <module>
    from database.db_manager import DatabaseManager
  File "/root/autodl-tmp/indexTTS/server/database/db_manager.py", line 11, in <module>
    from ..utils.file_manager import TaskFileManager
ImportError: attempted relative import beyond top-level package
INFO 09-28 16:02:47 [__init__.py:216] Automatically detected platform cuda.
✅  Registry GPT2TTSModel to vllm
✅  GPUModelRunner._prepare_inputs Patched
Traceback (most recent call last):
  File "/root/autodl-tmp/indexTTS/server/task_worker.py", line 38, in <module>
    from database.db_manager import DatabaseManager
  File "/root/autodl-tmp/indexTTS/server/database/db_manager.py", line 11, in <module>
    from ..utils.file_manager import TaskFileManager
ImportError: attempted relative import beyond top-level package
INFO 09-28 16:02:59 [__init__.py:216] Automatically detected platform cuda.
✅  Registry GPT2TTSModel to vllm
✅  GPUModelRunner._prepare_inputs Patched
Traceback (most recent call last):
  File "/root/autodl-tmp/indexTTS/server/task_worker.py", line 38, in <module>
    from database.db_manager import DatabaseManager
  File "/root/autodl-tmp/indexTTS/server/database/db_manager.py", line 11, in <module>
    from ..utils.file_manager import TaskFileManager
ImportError: attempted relative import beyond top-level package
INFO 09-28 16:03:10 [__init__.py:216] Automatically detected platform cuda.
✅  Registry GPT2TTSModel to vllm
✅  GPUModelRunner._prepare_inputs Patched
Traceback (most recent call last):
  File "/root/autodl-tmp/indexTTS/server/task_worker.py", line 38, in <module>
    from database.db_manager import DatabaseManager
  File "/root/autodl-tmp/indexTTS/server/database/db_manager.py", line 11, in <module>
    from ..utils.file_manager import TaskFileManager
ImportError: attempted relative import beyond top-level package
INFO 09-28 16:03:20 [__init__.py:216] Automatically detected platform cuda.
✅  Registry GPT2TTSModel to vllm
✅  GPUModelRunner._prepare_inputs Patched
Traceback (most recent call last):
  File "/root/autodl-tmp/indexTTS/server/task_worker.py", line 38, in <module>
    from database.db_manager import DatabaseManager
  File "/root/autodl-tmp/indexTTS/server/database/db_manager.py", line 11, in <module>
    from ..utils.file_manager import TaskFileManager
ImportError: attempted relative import beyond top-level package
INFO 09-28 16:03:30 [__init__.py:216] Automatically detected platform cuda.
✅  Registry GPT2TTSModel to vllm
✅  GPUModelRunner._prepare_inputs Patched
Traceback (most recent call last):
  File "/root/autodl-tmp/indexTTS/server/task_worker.py", line 38, in <module>
    from database.db_manager import DatabaseManager
  File "/root/autodl-tmp/indexTTS/server/database/db_manager.py", line 11, in <module>
    from ..utils.file_manager import TaskFileManager
ImportError: attempted relative import beyond top-level package
INFO 09-28 16:03:43 [__init__.py:216] Automatically detected platform cuda.
✅  Registry GPT2TTSModel to vllm
✅  GPUModelRunner._prepare_inputs Patched
Traceback (most recent call last):
  File "/root/autodl-tmp/indexTTS/server/task_worker.py", line 38, in <module>
    from database.db_manager import DatabaseManager
  File "/root/autodl-tmp/indexTTS/server/database/db_manager.py", line 11, in <module>
    from ..utils.file_manager import TaskFileManager
ImportError: attempted relative import beyond top-level package
INFO 09-28 16:03:56 [__init__.py:216] Automatically detected platform cuda.
✅  Registry GPT2TTSModel to vllm
✅  GPUModelRunner._prepare_inputs Patched
Traceback (most recent call last):
  File "/root/autodl-tmp/indexTTS/server/task_worker.py", line 38, in <module>
    from database.db_manager import DatabaseManager
  File "/root/autodl-tmp/indexTTS/server/database/db_manager.py", line 11, in <module>
    from ..utils.file_manager import TaskFileManager
ImportError: attempted relative import beyond top-level package
